# Generated by Django 4.1.4 on 2022-12-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe', models.CharField(default='equipe', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ligue', models.CharField(default='ligue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_match', models.CharField(default='match', max_length=20)),
                ('date_match', models.DateTimeField(null=True, verbose_name='Date du match')),
                ('ligue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligues.ligue')),
                ('locaux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='ligues.equipe')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiteurs', to='ligues.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligues.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='ligue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligues.ligue'),
        ),
    ]
