# Generated by Django 4.1.4 on 2022-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='nom_joueur',
            field=models.CharField(default='nom_joueur', max_length=20),
        ),
    ]
