# Generated by Django 4.1.4 on 2022-12-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0003_alter_match_nom_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='visiteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiteur', to='ligues.equipe'),
        ),
    ]
