# Generated by Django 4.1.4 on 2022-12-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0004_alter_match_visiteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='but_loc',
            field=models.IntegerField(default=0),
        ),
    ]
