# Generated by Django 4.1.4 on 2022-12-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0005_match_but_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='but_loc',
            new_name='But(s) Locaux',
        ),
        migrations.AddField(
            model_name='match',
            name='But(s) Visiteurs',
            field=models.IntegerField(default=0),
        ),
    ]
