# Generated by Django 4.1.4 on 2022-12-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0006_rename_but_loc_match_but(s) locaux_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='But(s) Locaux',
            new_name='But_Locaux',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='But(s) Visiteurs',
            new_name='But_Visiteurs',
        ),
    ]
