# Generated by Django 4.1.4 on 2022-12-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0007_rename_but(s) locaux_match_but_locaux_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='But_Locaux',
            new_name='but_loc',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='But_Visiteurs',
            new_name='but_vis',
        ),
    ]
