# Generated by Django 4.1.4 on 2022-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0008_rename_but_locaux_match_but_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_match',
            field=models.DateField(null=True, verbose_name='Date du match'),
        ),
    ]
