# Generated by Django 4.1.4 on 2022-12-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligues', '0009_alter_match_date_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='img',
            field=models.CharField(default='img', max_length=100),
        ),
    ]
